<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="991" started-at="2019-12-05T03:43:09Z" finished-at="2019-12-05T03:43:10Z">
    <groups>
      <group name="regression">
        <method signature="TestClass1.m1(java.lang.String)[pri:1, instance:TestngActPack.TestClass1@64bf3bbf]" name="m1" class="TestngActPack.TestClass1"/>
        <method signature="TestClass1.m3()[pri:2, instance:TestngActPack.TestClass1@64bf3bbf]" name="m3" class="TestngActPack.TestClass1"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="TestClass1.m1(java.lang.String)[pri:1, instance:TestngActPack.TestClass1@64bf3bbf]" name="m1" class="TestngActPack.TestClass1"/>
        <method signature="TestClass1.m2()[pri:0, instance:TestngActPack.TestClass1@64bf3bbf]" name="m2" class="TestngActPack.TestClass1"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Test" duration-ms="991" started-at="2019-12-05T03:43:09Z" finished-at="2019-12-05T03:43:10Z">
      <class name="TestngActPack.TestClass1">
        <test-method status="PASS" signature="betest()[pri:0, instance:TestngActPack.TestClass1@64bf3bbf]" name="betest" is-config="true" duration-ms="429" started-at="2019-12-05T09:13:09Z" finished-at="2019-12-05T09:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- betest -->
        <test-method status="PASS" signature="m2()[pri:0, instance:TestngActPack.TestClass1@64bf3bbf]" name="m2" duration-ms="8" started-at="2019-12-05T09:13:10Z" finished-at="2019-12-05T09:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="PASS" signature="m1(java.lang.String)[pri:1, instance:TestngActPack.TestClass1@64bf3bbf]" name="m1" duration-ms="4" started-at="2019-12-05T09:13:10Z" description="test case 1" finished-at="2019-12-05T09:13:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
        <test-method status="SKIP" signature="m3()[pri:2, instance:TestngActPack.TestClass1@64bf3bbf]" name="m3" duration-ms="14" started-at="2019-12-05T09:13:10Z" finished-at="2019-12-05T09:13:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at TestngActPack.TestClass1.m3(TestClass1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="SKIP" signature="m3()[pri:2, instance:TestngActPack.TestClass1@64bf3bbf]" name="m3" duration-ms="2" started-at="2019-12-05T09:13:10Z" finished-at="2019-12-05T09:13:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at TestngActPack.TestClass1.m3(TestClass1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="FAIL" signature="m3()[pri:2, instance:TestngActPack.TestClass1@64bf3bbf]" name="m3" duration-ms="2" started-at="2019-12-05T09:13:10Z" finished-at="2019-12-05T09:13:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at TestngActPack.TestClass1.m3(TestClass1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:TestngActPack.TestClass1@64bf3bbf]" name="afterTest" is-config="true" duration-ms="481" started-at="2019-12-05T09:13:10Z" finished-at="2019-12-05T09:13:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- TestngActPack.TestClass1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
